apiVersion: v1
kind: Service
metadata:
  name: flask-server2-service
spec:
  selector:
    app: flask-server2
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081
  type: LoadBalancer
