apiVersion: v1
kind: Service
metadata:
  name: server-1-service
spec:
  selector:
    app: server-1
  ports:
    - protocol: TCP
      port: 8000       
      targetPort: 8000   
  type: LoadBalancer    
