apiVersion: v1
kind: Service
metadata:
  name: flask-server1-service
spec:
  selector:
    app: flask-server1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 
  type: LoadBalancer
