apiVersion: v1
kind: Pod
metadata:
  name: server-1-pod

spec:
  containers:
    - name: server-1-ctr
      image: localhost:5000/sayandeeps/server1:latest
      ports:
        - containerPort: 8000
      imagePullPolicy: Always

